-- MySQL Script generated by MySQL Workbench
-- Tue Dec  7 09:49:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dumplings
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dumplings
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dumplings` DEFAULT CHARACTER SET utf8mb4 ;
USE `dumplings` ;

-- -----------------------------------------------------
-- Table `dumplings`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`users` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `name` VARCHAR(100) NULL,
    `email` VARCHAR(100) NULL,
    `email_verified_at` TIMESTAMP NULL,
    `password` VARCHAR(100) NULL,
    `remember_token` VARCHAR(100) NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`subscribers` (
                                                         `id` INT NOT NULL AUTO_INCREMENT,
                                                         `name` VARCHAR(100) NULL,
    `email` VARCHAR(100) NULL,
    `receives_newsletter` TINYINT NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    `language_iso_code` VARCHAR(4) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`newsletters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`newsletters` (
                                                         `id` INT NOT NULL AUTO_INCREMENT,
                                                         `subject_de` VARCHAR(255) NULL,
    `headline_de` VARCHAR(255) NULL,
    `body_de` TEXT NULL,
    `subject_en` VARCHAR(255) NULL,
    `headline_en` VARCHAR(255) NULL,
    `body_en` TEXT NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    `last_send_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`news` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `headline_de` VARCHAR(255) NULL,
    `body_de` TEXT NULL,
    `headline_en` VARCHAR(255) NULL,
    `body_en` TEXT NULL,
    `image_path` VARCHAR(255) NULL,
    `image_file_name` VARCHAR(255) NULL,
    `display_from` DATE NULL,
    `display_to` DATE NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`stories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`stories` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `is_visible_to_frontend` TINYINT NULL,
                                                     `headline_de` VARCHAR(255) NULL,
    `body_de` TEXT NULL,
    `headline_en` VARCHAR(255) NULL,
    `body_en` TEXT NULL,
    `image_path` VARCHAR(255) NULL,
    `image_file_name` VARCHAR(255) NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`footer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`footer` (
                                                    `id` INT NOT NULL,
                                                    `company_info_headline_de` VARCHAR(255) NULL,
    `company_info_body_de` TEXT NULL,
    `company_info_headline_en` VARCHAR(255) NULL,
    `company_info_body_en` TEXT NULL,
    `contact_info_addresse` VARCHAR(255) NULL,
    `contact_info_phone` VARCHAR(255) NULL,
    `contact_info_email` VARCHAR(255) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`foodlist_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`foodlist_categories` (
                                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                                 `label_en` VARCHAR(255) NULL,
    `label_de` VARCHAR(255) NULL,
    `image_path` VARCHAR(255) NULL,
    `category_information_de` VARCHAR(255) NULL,
    `category_information_en` VARCHAR(255) NULL,
    `category_second_information_de` VARCHAR(255) NULL,
    `category_second_information_en` VARCHAR(255) NULL,
    `context_type_de` VARCHAR(255) NULL,
    `image_file_name` VARCHAR(255) NULL,
    `footline_de` VARCHAR(255) NULL,
    `footline_en` VARCHAR(255) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`foodlist_sub_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`foodlist_sub_categories` (
                                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                                     `label_en` VARCHAR(255) NULL,
    `label_de` VARCHAR(255) NULL,
    `sub_category_information_de` TEXT NULL,
    `sub_category_information_en` TEXT NULL,
    `is_halal` TINYINT(1) NULL,
    `is_vegan` TINYINT(1) NULL,
    `is_veggie` TINYINT(1) NULL,
    `is_spicy` TINYINT(1) NULL,
    `spicy_level` TINYINT(1) NULL,
    `foodlist_categories_id` INT NOT NULL,
    `container_size` VARCHAR(255) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`foodlist_entries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`foodlist_entries` (
                                                              `id` INT NOT NULL AUTO_INCREMENT,
                                                              `label_en` VARCHAR(255) NULL,
    `label_de` VARCHAR(255) NULL,
    `foodlist_information_de` VARCHAR(255) NULL,
    `foodlist_information_en` VARCHAR(255) NULL,
    `is_halal` TINYINT(1) NULL,
    `is_vegan` TINYINT(1) NULL,
    `is_veggie` TINYINT(1) NULL,
    `is_spicy` TINYINT(1) NULL,
    `spicy_level` TINYINT(1) NULL,
    `foodlist_sub_categories_id` INT NOT NULL,
    `container_size` VARCHAR(255) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`foodlist_extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`foodlist_extras` (
                                                             `id` INT NOT NULL AUTO_INCREMENT,
                                                             `label_en` VARCHAR(255) NULL,
    `label_de` VARCHAR(255) NULL,
    `is_halal` TINYINT(1) NULL,
    `is_vegan` TINYINT(1) NULL,
    `is_veggie` TINYINT(1) NULL,
    `is_spicy` TINYINT(1) NULL,
    `spicy_level` TINYINT(1) NULL,
    `foodlist_entries_id` INT NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
