-- MySQL Script generated by MySQL Workbench
-- Sun Oct 17 08:50:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dumplings
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dumplings
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dumplings` DEFAULT CHARACTER SET utf8mb4 ;
USE `dumplings` ;

-- -----------------------------------------------------
-- Table `dumplings`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `email_verified_at` TIMESTAMP NULL,
  `password` VARCHAR(100) NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`subscribers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `is_active` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NULL,
  `context` ENUM('Newsletter', 'News', 'Speisekarte') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`newsletters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`newsletters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `heading` VARCHAR(100) NULL,
  `second_heading` VARCHAR(100) NULL,
  `subject` VARCHAR(100) NULL,
  `content` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NULL,
  `filename` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `heading` VARCHAR(100) NULL,
  `content` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `start` DATE NULL,
  `end` DATE NULL,
  `category_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`foodlist_entries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`foodlist_entries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `content` TEXT NULL,
  `is_active` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `category_id` INT NOT NULL,
  `image_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`newsletter_subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`newsletter_subscribers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_send_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `subscriber_id` INT NOT NULL,
  `newsletter_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`foodlist_sorting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`foodlist_sorting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foodlist_entry_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `position` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dumplings`.`stories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dumplings`.`stories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `heading` VARCHAR(255) NULL,
  `content` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `is_active` TINYINT NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
